# Feed conf
rss:
  feed_just_link: https://blog1.website.net/rss
  my_blog:
    url: https://blog.my-site.org/feed
    color: 0xefd613  # Hex value of embeds for this feed, default val
    simple_link: no  # If set to yes, then only links are sent (so that Discord will load the embed from the link), so they are plain text messages.
    interval: null   # For overwrite crawl check interval, in minutes, minimum is 10 minutes

# Hooks conf
webhooks:
  name_of_webhook:
    url: https://discord.com/...
    subs:  # List of feeds
      - feed_just_link
      - my_blog